import { CalendarDays, Folder } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { useParams } from 'react-router-dom';
import { articleApi } from '../../api';
import { LoadingSkeleton, ErrorState, EmptyState } from '../../components/AsyncStates';
import MarkdownRenderer from '../../components/MarkdownRenderer';

export default function ArticleReadPage(){ const {articleCode}=useParams(); const [article,setArticle]=useState<any>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); async function load(){try{setLoading(true); setError(null); setArticle(await articleApi.getDetail(articleCode));}catch(e:any){setError(e.message)}finally{setLoading(false)}} useEffect(()=>{load()},[articleCode]); const toc=useMemo(()=>((article?.contentMd||'').match(/^#{1,6}\s+.+$/gm)||[]).map((h:string,i:number)=>({id:slug(h.replace(/^#+\s+/,'')), text:h.replace(/^#+\s+/,''), level:(h.match(/^#+/)?.[0].length||1)})),[article]); if(loading)return <div className="page-container"><LoadingSkeleton title rows={8}/></div>; if(error)return <div className="page-container"><ErrorState message={error} onRetry={load}/></div>; if(!article)return <div className="page-container"><EmptyState title="게시글을 찾을 수 없습니다."/></div>; return <div className="article-read-layout"><article className="article-content"><h1 className="article-title">{article.title}</h1><div className="article-meta"><span><Folder size={15}/>{article.folderTitle||'Uncategorized'}</span><span><CalendarDays size={15}/>{formatDate(article.publishedAt||article.updatedAt)}</span></div><MarkdownRenderer content={article.contentMd}/></article><aside className="toc-sidebar"><div className="outline-panel"><p className="outline-title">ON THIS PAGE</p>{toc.length===0?<p className="muted-text">목차 없음</p>:toc.map((t:any)=><button key={t.id} style={{paddingLeft:(t.level-1)*12}} onClick={()=>document.getElementById(t.id)?.scrollIntoView({behavior:'smooth'})}>{t.text}</button>)}</div></aside></div> }
function slug(text:any){return String(text).toLowerCase().replace(/[^a-z0-9가-힣]+/g,'-').replace(/(^-|-$)/g,'')} function formatDate(v?:string){return v?new Date(v).toLocaleString('ko-KR'):'-'}
