import { ArrowRight, FolderOpen, Search } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { folderApi, searchApi } from '../../api';
import { LoadingSkeleton, EmptyState, ErrorState } from '../../components/AsyncStates';
import DataTable from '../../components/DataTable';

export default function PortalHomePage(){ const navigate=useNavigate(); const [folders,setFolders]=useState<any[]>([]); const [articles,setArticles]=useState<any[]>([]); const [keyword,setKeyword]=useState(''); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); async function load(){try{setLoading(true);setError(null); const [fs,as]=await Promise.all([folderApi.getRoots(true), searchApi.search(keyword,true)]); setFolders(fs||[]); setArticles(as||[]);}catch(e:any){setError(e.message)}finally{setLoading(false)}} useEffect(()=>{load()},[]); async function search(){try{setLoading(true); setArticles(await searchApi.search(keyword,true));}catch(e:any){setError(e.message)}finally{setLoading(false)}} return <div className="page-container"><section className="portal-hero"><div><span className="eyebrow">CMS Portal</span><h1>필요한 문서를 빠르게 탐색하세요.</h1><p>발행된 콘텐츠만 노출되는 안전하고 명확한 지식 포털입니다.</p></div><div className="hero-search"><Search size={20}/><input value={keyword} onChange={e=>setKeyword(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search()} placeholder="제목 또는 본문 검색"/><button onClick={search}>검색</button></div></section>{error&&<ErrorState message={error} onRetry={load}/>}<div className="section-header"><h2>카테고리</h2></div>{loading ? <LoadingSkeleton rows={3}/> : folders.length===0 ? <EmptyState title="카테고리가 없습니다."/> : <div className="folder-grid">{folders.map(f=><button className="folder-card" key={f.folderCode} onClick={()=>navigate(`/portal/folder/${f.folderCode}`)}><FolderOpen/><strong>{f.title}</strong><p>{f.description||'콘텐츠 폴더'}</p><span>열기 <ArrowRight size={14}/></span></button>)}</div>}<div className="section-header"><h2>최근 게시글</h2></div><DataTable columns={[{key:'title',label:'제목',render:(v,r)=><div><strong>{v}</strong><p className="muted-text">{(r.contentMd||'').slice(0,90)}</p></div>},{key:'folderTitle',label:'폴더'},{key:'publishedAt',label:'발행일',render:v=>formatDate(v)}]} data={articles} loading={loading} error={null} emptyTitle="발행된 게시글이 없습니다." onRowClick={r=>navigate(`/portal/article/${r.articleCode}`)}/></div> }
function formatDate(v?:string){return v?new Date(v).toLocaleDateString('ko-KR'):'-'}
