import { LockKeyhole, UserRound } from 'lucide-react';
import { useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { authApi } from '../api';
import { useAuthStore } from '../store/auth-store';
import { Button } from '../components/ui/Button';
import { Input, Label } from '../components/ui/Input';

export default function LoginPage(){ const [username,setUsername]=useState('admin'); const [password,setPassword]=useState(''); const [loading,setLoading]=useState(false); const [error,setError]=useState<string|null>(null); const login=useAuthStore(s=>s.login); const navigate=useNavigate(); const location:any=useLocation(); async function submit(e:any){e.preventDefault(); try{setLoading(true); setError(null); const res=await authApi.login({username,password}); login(res.token, res.username || username); navigate(location.state?.from?.pathname || '/admin');}catch(e:any){setError(e.message||'로그인 실패');}finally{setLoading(false);}} return <div className="login-page"><section className="login-hero"><div className="hero-pill">CMS Content Platform</div><h1>전문적인 콘텐츠 운영을 위한 모던 SaaS CMS</h1><p>폴더 트리, Markdown 편집, 발행 워크플로우를 하나의 깔끔한 관리자 경험으로 제공합니다.</p><div className="hero-metrics"><span>JWT Secure</span><span>Markdown</span><span>Portal/Admin</span></div></section><section className="login-card"><Link to="/portal" className="brand-mark login-brand"><span className="brand-logo">C</span><span>CMS</span></Link><h2>관리자 로그인</h2><p>계속하려면 계정 정보를 입력하세요.</p>{error&&<div className="error-banner">{error}</div>}<form onSubmit={submit} className="form-body"><div className="form-field"><Label required>Username</Label><Input icon={<UserRound size={16}/>} value={username} onChange={e=>setUsername(e.target.value)} /></div><div className="form-field"><Label required>Password</Label><Input icon={<LockKeyhole size={16}/>} type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="비밀번호" /></div><Button loading={loading} className="w-full">로그인</Button></form><p className="caption">관리자 계정은 초기 데이터로 제공됩니다. <span>/admin/register</span></p></section></div> }
