import { FileText, FolderOpen, PenLine, PlusCircle } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { folderApi, searchApi } from '../../api';
import { LoadingSkeleton, ErrorState, EmptyState } from '../../components/AsyncStates';
import StatusBadge from '../../components/StatusBadge';

export default function AdminHomePage(){ const nav=useNavigate(); const [folders,setFolders]=useState<any[]>([]); const [articles,setArticles]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); async function load(){try{setLoading(true);setError(null); const [fs,as]=await Promise.all([folderApi.getRoots(false), searchApi.search('',false)]); setFolders(fs||[]); setArticles(as||[]);}catch(e:any){setError(e.message)}finally{setLoading(false)}} useEffect(()=>{load()},[]); const draft=articles.filter(a=>a.status==='DRAFT').length; if(error)return <div className="page-container"><ErrorState message={error} onRetry={load}/></div>; return <div className="dashboard-page"><div className="dashboard-hero"><div><span className="eyebrow">Admin Dashboard</span><h1>콘텐츠 운영 현황</h1><p>게시글 작성, 발행 상태, 폴더 구조를 한눈에 관리하세요.</p></div><button className="btn btn-primary btn-lg" onClick={()=>nav('/admin/article/new')}><PlusCircle size={18}/> 새 게시글</button></div>{loading?<LoadingSkeleton rows={6}/>:<><div className="kpi-grid"><Metric icon={<FolderOpen/>} label="폴더" value={folders.length}/><Metric icon={<FileText/>} label="게시글" value={articles.length}/><Metric icon={<PenLine/>} label="초안" value={draft}/></div><div className="dashboard-bottom"><section className="recent-section"><div className="section-header"><h2>최근 게시글</h2><button onClick={()=>nav('/admin/articles')}>전체 보기</button></div>{articles.length===0?<EmptyState title="게시글이 없습니다."/>:<div className="recent-list">{articles.slice(0,6).map(a=><button className="recent-item" key={a.articleCode} onClick={()=>nav(`/admin/article/${a.articleCode}`)}><div className="recent-thumb"><FileText size={18}/></div><div className="recent-body"><p className="recent-title">{a.title}</p><div className="recent-meta"><span>{a.folderTitle||'Uncategorized'}</span><span>{formatDate(a.updatedAt)}</span></div></div><StatusBadge status={a.status}/></button>)}</div>}</section><section className="activity-card"><h3>Quick Actions</h3><button className="quick-action" onClick={()=>nav('/admin/article/new')}>새 게시글 작성</button><button className="quick-action" onClick={()=>nav('/admin/folder')}>폴더 관리</button><button className="quick-action" onClick={()=>nav('/portal')}>포털 확인</button></section></div></>}</div> }
function Metric({icon,label,value}:any){return <div className="kpi-metric"><div className="kpi-icon">{icon}</div><p className="kpi-label">{label}</p><p className="kpi-value">{value}</p></div>} function formatDate(v?:string){return v?new Date(v).toLocaleDateString('ko-KR'):'-'}
