import { PlusCircle } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { searchApi } from '../../api';
import DataTable from '../../components/DataTable';
import StatusBadge from '../../components/StatusBadge';

export default function ArticleListPage(){ const nav=useNavigate(); const [keyword,setKeyword]=useState(''); const [status,setStatus]=useState('ALL'); const [data,setData]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); async function load(){try{setLoading(true);setError(null); setData(await searchApi.search(keyword,false));}catch(e:any){setError(e.message)}finally{setLoading(false)}} useEffect(()=>{load()},[]); const filtered=useMemo(()=>status==='ALL'?data:data.filter(a=>a.status===status),[data,status]); return <div className="page-container"><div className="page-header"><div><span className="eyebrow">Articles</span><h1 className="page-title">게시글 관리</h1></div><button className="btn btn-primary btn-md" onClick={()=>nav('/admin/article/new')}><PlusCircle size={17}/> 새 게시글</button></div><div className="filter-bar"><input className="search-input" value={keyword} onChange={e=>setKeyword(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="제목/본문 검색"/><button className="btn btn-outline btn-md" onClick={load}>검색</button><div className="segmented">{['ALL','DRAFT','PUBLISHED','OFFLINE'].map(s=><button key={s} className={status===s?'active':''} onClick={()=>setStatus(s)}>{s}</button>)}</div></div><DataTable columns={[{key:'no',label:'번호',render:(_,__,i)=>i+1},{key:'title',label:'제목',render:v=><strong>{v}</strong>},{key:'folderTitle',label:'폴더',render:v=>v||'-'},{key:'status',label:'상태',render:v=><StatusBadge status={v}/>},{key:'updatedAt',label:'수정일',render:v=>formatDate(v)}]} data={filtered} loading={loading} error={error} onRetry={load} emptyTitle="게시글이 없습니다." onRowClick={r=>nav(`/admin/article/${r.articleCode}`)}/></div> }
function formatDate(v?:string){return v?new Date(v).toLocaleString('ko-KR'):'-'}
